# Numpy

* Arrays

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]

In [ ]:
a = np.array([
    [1,2],
    [3,4]
])

print(a)

[[1 2]
 [3 4]]

* Indexing

In [ ]:
a = np.array([1,2,3,4,5])

print(a[0])

1

In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a[1][0])

4

* Slicing

In [ ]:
a= np.array([1,2,3,4,5])

print(a[0::2])

[1 3 5]

In [ ]:
a =np.array ([
    [1,2,3,4],
    [5,6,7,8]
])

print(a[:,1:])

[[2 3 4]
 [6 7 8]]

* Reshape

In [ ]:
a = np.array([1,2,3,4,5,6])

print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]

* Broadcasting

In [ ]:
a= np.array([1,2,3,4,5])
# you can perform any mathamtical operations
print(a+5)

[ 6  7  8  9 10]

* Statistics Functions

In [ ]:
a = np.array([1,2,3,4,5,6])

print(a.min())
print(a.max())
print(a.prod())
print(a.sum())
print(np.median(a))
print(np.std(a))

1
6
720
21
3.5
1.707825127659933

* Random Module

In [ ]:
print(np.random.rand(3))

[0.37779382 0.66574762 0.37367353]

In [ ]:
print(np.random.rand(1,10,3))

[[[0.70995981 0.33878158 0.4837912 ]
  [0.4537118  0.76807365 0.04206935]
  [0.87839789 0.81497832 0.35409997]
  [0.12751374 0.43365476 0.3044381 ]
  [0.9785807  0.74914698 0.87908281]
  [0.64725771 0.53252331 0.3420418 ]
  [0.53532103 0.21633771 0.5501043 ]
  [0.35261137 0.05998987 0.42935899]
  [0.5331819  0.30892508 0.75021558]
  [0.38689687 0.91086648 0.77050804]]]

# Pandas

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name": ["Kedar", "Rahul"],
    "Marks": [80, 90]
}


df=pd.DataFrame(data)
print(df)

    Name  Marks
0  Kedar     80
1  Rahul     90

In [ ]:
# Single column.

df = pd.Series([10,20,30])

print(df)

0    10
1    20
2    30
dtype: int64

* Head

In [ ]:
df = pd.Series([10,20,55,2])

print(df.head(1))

0    10
dtype: int64

* Tail

In [ ]:
print(df.tail(1))

3    2
dtype: int64

* loc

In [ ]:
hospital = pd.read_csv('/content/diabetes.csv')
movie = pd.read_csv('/content/movies.csv')

print(df1.loc[0])

Pregnancies                   6.000
Glucose                     148.000
BloodPressure                72.000
SkinThickness                35.000
Insulin                       0.000
BMI                          33.600
DiabetesPedigreeFunction      0.627
Age                          50.000
Outcome                       1.000
Name: 0, dtype: float64

In [ ]:
df = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie'],
    'age':   [25, 30, 35],
    'score': [88, 92, 79]
})

In [ ]:
df.loc[0]

name     Alice
age         25
score       88
Name: 0, dtype: object

In [ ]:
df.loc[0, 'name']    # → 'Alice'
df.loc[1, 'age']     # → 30

np.int64(30)

* iloc

In [ ]:
df = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie'],
    'age':   [25, 30, 35],
    'score': [88, 92, 79]
})

In [ ]:
df.iloc[1,2]

np.int64(92)

* groupby()

In [ ]:
data = {
    "Dept": ["IT", "IT", "HR"],
    "Salary": [50000,60000,40000]
}


df=pd.DataFrame(data)

df.groupby('Dept')['Salary'].mean()

Dept
HR    40000.0
IT    55000.0
Name: Salary, dtype: float64

* Sorting

In [ ]:
df.sort_values('Salary',ascending=False)

  Dept  Salary
1   IT   60000
0   IT   50000
2   HR   40000

In [ ]:
df.sort_index()

  Dept  Salary
2   HR   40000
1   IT   60000
0   IT   50000

* Handling Null Values

In [ ]:
print(df.isnull())

    Dept  Salary
0  False   False
1  False   False
2  False   False

* removes null values

In [ ]:
df.dropna()

  Dept  Salary
0   IT   50000
1   IT   60000
2   HR   40000

* Fill nulls

In [ ]:
print(df.fillna(0))

  Dept  Salary
0   IT   50000
1   IT   60000
2   HR   40000

* merge() / join()

In [ ]:
df= pd.DataFrame({
    'Name':['Kedar','Om','Sam'],
    'ID':[10,20,30]

}
)

df1=pd.DataFrame({
    'ID':[10,20,30],
    'year':[2023,2025,2024]
    })


print(pd.merge(df,df1, on = "ID"))

    Name  ID  year
0  Kedar  10  2023
1     Om  20  2025
2    Sam  30  2024

Scenario
A retail company has recorded weekly sales (in ₹ thousands) for 4 stores over 12 weeks. The data arrived as a flat 1D array of 48 values with some entries corrupted as np.nan. Your task is to restructure and analyze it.
Tasks
Reshape the 1D array into a (4, 12) matrix — rows = stores, columns = weeks.
Replace all NaN values with the column (weekly) mean across non-NaN stores.
Find the top-performing store (highest total annual sales).
Flag weeks where ALL stores sold below ₹50k (boolean mask).
Compute cumulative sales per store across the 12 weeks.

In [47]:
import numpy as np

arr = np.random.randint(1000, 2000, 48).astype(float)

arr = arr.reshape(4, 12)

print("Original Array:")
print(arr)
arr[0, 2] = np.nan
arr[2, 5] = np.nan

# Replace NaN with column mean
col_mean = np.nanmean(arr, axis=0)

rows, cols = np.where(np.isnan(arr))

arr[rows, cols] = col_mean[cols]

print("\nSales Matrix After Replacing NaN:")
print(arr)

# Top-performing store
store_sales = np.sum(arr, axis=1)

top_store = np.argmax(store_sales)

print("\nTop Performing Store:")
print(f"Store {top_store + 1}")

print("\nStore Sales:")
print(store_sales)

# Flag low-sales weeks
low_sales_weeks = np.all(arr < 50, axis=0)

print("\nWeeks Where All Stores Sold Below 50:")
print(low_sales_weeks)

# Cumulative sales per store
cumulative_sales = np.cumsum(arr, axis=1)

print("\nCumulative Sales Per Store:")
print(cumulative_sales)

Original Array:
[[1125. 1554. 1360. 1630. 1301. 1555. 1365. 1573. 1198. 1909. 1569. 1754.]
 [1133. 1818. 1795. 1326. 1642. 1766. 1943. 1583. 1881. 1938. 1449. 1382.]
 [1084. 1087. 1879. 1505. 1080. 1784. 1223. 1192. 1808. 1564. 1845. 1531.]
 [1057. 1576. 1578. 1404. 1979. 1031. 1525. 1552. 1314. 1883. 1561. 1739.]]

Sales Matrix After Replacing NaN:
[[1125.         1554.         1750.66666667 1630.         1301.
  1555.         1365.         1573.         1198.         1909.
  1569.         1754.        ]
 [1133.         1818.         1795.         1326.         1642.
  1766.         1943.         1583.         1881.         1938.
  1449.         1382.        ]
 [1084.         1087.         1879.         1505.         1080.
  1450.66666667 1223.         1192.         1808.         1564.
  1845.         1531.        ]
 [1057.         1576.         1578.         1404.         1979.
  1031.         1525.         1552.         1314.         1883.
  1561.         1739.        ]]

Top Performing Store:
Store 2

Store Sales:
[18283.66666667 19656.         17248.66666667 18199.        ]

Weeks Where All Stores Sold Below 50:
[False False False False False False False False False False False False]

Cumulative Sales Per Store:
[[ 1125.          2679.          4429.66666667  6059.66666667
   7360.66666667  8915.66666667 10280.66666667 11853.66666667
  13051.66666667 14960.66666667 16529.66666667 18283.66666667]
 [ 1133.          2951.          4746.          6072.
   7714.          9480.         11423.         13006.
  14887.         16825.         18274.         19656.        ]
 [ 1084.          2171.          4050.          5555.
   6635.          8085.66666667  9308.66666667 10500.66666667
  12308.66666667 13872.66666667 15717.66666667 17248.66666667]
 [ 1057.          2633.          4211.          5615.
   7594.          8625.         10150.         11702.
  13016.         14899.         16460.         18199.        ]]